# 日志相关配置
[Logging]
    LogPath = "./log"
    LogFile = "main.log"
    FileLevel = "DEBUG"
    ConsoleLevel = "DEBUG"
    MaxAge = 7
    MaxSize = 10

[API]
    Host = "192.168.1.100"
    Port = 6060

    # 企业微信后台推送预警数据授权
    [API.WeCom]
    AppId = "432a8nc4"
    AppSecret = "a8f224aea83a97ed395c75df6fe3a889"

[ORM]
    DSN = "root:123456@tcp(192.168.1.100:3306)/fzmps?timeout=10s&readTimeout=10s&writeTimeout=10s&parseTime=true&loc=Local&charset=utf8mb4"
    Active = 100
    Idle = 5
    IdleTimeout = "10m"

[Services]
    # 腾讯逆地址解析服务
    # https://lbs.qq.com/service/webService/webServiceGuide/webServiceGcoder
    [Services.Location]
    Key = "QEQBZ-SOCH6-FV2SP-M3X3K-J2TRK-Y3BZB"

    # 小程序后台对接微信平台授权
    [Services.MiniPro]
    AppId = "wx1c6ad71e0dce8110"
    AppSecret = "a02090353df1fb2b77f013093b69a367"

    # 推送微信用户unionid数据到企业微信
    [Services.WeCom]
    AppId = "5e369j53"
    AppSecret = "be2f9f82efca04d5c80e9420c79a5027"
    PushUrl = "http://192.168.1.100:8081/api/wechatContactInfo"
